import React, { useState } from "react";
import { servicesAPI } from "../../services/api";

interface DataModificationFormProps {
  onServiceAdded: () => void;
}

const USER_COLUMNS = ["HENGI", "MARLENI", "ISRAEL", "THAICAR"];

const SERVICE_LIST = [
  "SERVICIO REDACCION CONTRATO LEGAL",
  "SERVICIO REDACCION CONTRATO NOTARIAL",
  "SERVICIO REDACCION INSTANCIA",
  "SERVICIO REDACCION INSTANCIA EXTENSA",
  "SERVICIO REDACCION ESCRITO AMPLIO",
  "SERVICIO REDACCION COLETILLA",
  "SERVICIO REDACCION TRADUCCION JUDICIAL",
  "SERVICIO REDACCION NOTIFICACION",
  "SERVICIO REDACCION TRADUCCION JUDICIAL EXTENSA",
  "SERVICIO DE REDACCION OTROS",
  "SERVICIO FORMATO E IMPRESION",
  "SERVICIO DE IMPRESION",
  "SERVICIO DE IMPRESION DOCUMENTO LEGAL",
  "SERVICIO DE IMPRESION DOCUMENTO NORMAL",
  "SERVICIO DE IMPRESION FOTO 2x2",
  "SERVICIO DE COPIA BLANCO Y NEGRO",
  "SERVICIO DE COPIA A COLOR",
  "SERVICIO DE ESCANER DOCUMENTO DIGITAL",
  "SERVICIO SOLICITUD CERTIFICACION APOSTILLE",
  "SERVICIO SOLICITUD CERTIFICACION VIAJE DE MENOR",
  "SERVICIO SOLICITUD CERTIFICACION ESTATUS JURIDICO DE INMUEBLE",
  "SERVICIO SOLICITUD INSCRIPCION DE INMUEBLE",
  "SERVICIO SOLICITUD CERTIFICACION CAMARA DE COMERCIO",
  "SERVICIO SOLICITUD DE CERTIFICACION PROCURADURIA GENERAL",
  "SERVICIO SOLICITUD DE CERTIFICACION ANTECEDENTES NO PENALES",
  "SERVICIO SOLICITUD DE CERTIFICACION OTROS",
  "SERVICIO MENSAJERIA",
  "SERVICIO MENSAJERIA COMPRA IMPUESTOS",
  "SERVICIO MENSAJERIA DEPOSITO DOCUMENTOS",
  "SERVICIO COMPRA IMPUESTOS",
];

const DataModificationForm: React.FC<DataModificationFormProps> = ({
  onServiceAdded,
}) => {
  const [selectedUser, setSelectedUser] = useState<string>(USER_COLUMNS[0]);
  const [serviceName, setServiceName] = useState<string>(SERVICE_LIST[0]);
  const [client, setClient] = useState<string>("");
  const [earnings, setEarnings] = useState<string>("");
  const [isFormOpen, setIsFormOpen] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    if (!serviceName.trim()) {
      setError("Por favor seleccione un servicio");
      setLoading(false);
      return;
    }

    const earningsNum = Number(earnings);
    if (isNaN(earningsNum) || earningsNum <= 0) {
      setError("Por favor ingrese una ganancia válida");
      setLoading(false);
      return;
    }

    try {
      await servicesAPI.createService({
        username: selectedUser,
        serviceName,
        client: client || undefined,
        earnings: earningsNum,
        // time is auto-generated by backend now
      });

      // Reset form
      setServiceName(SERVICE_LIST[0]);
      setClient("");
      setEarnings("");
      setIsFormOpen(false);

      // Notify parent to refresh data
      onServiceAdded();
    } catch (err: any) {
      setError(err.response?.data?.error || "Error al agregar servicio");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="overflow-hidden rounded-lg border border-slate-700 bg-slate-800 shadow-xl">
      <div className="flex items-center justify-between gap-2 border-b border-slate-700 bg-slate-900/50 px-3 py-3 sm:px-4">
        <h3 className="min-w-0 text-sm font-bold text-white sm:text-lg">Modificar Datos</h3>
        <button
          onClick={() => setIsFormOpen(!isFormOpen)}
          className="flex-shrink-0 rounded-lg border border-blue-900/30 bg-blue-600/20 px-3 py-1.5 text-xs text-blue-300 hover:bg-blue-600/30 sm:px-4 sm:py-2 sm:text-sm"
        >
          {isFormOpen ? "Cancelar" : "Agregar Servicio"}
        </button>
      </div>

      {isFormOpen && (
        <div className="p-4">
          <form onSubmit={handleSubmit} className="space-y-4">
            {error && (
              <div className="rounded-md border border-red-900/30 bg-red-500/20 p-3 text-center text-red-300">
                {error}
              </div>
            )}

            <div>
              <label
                htmlFor="user"
                className="mb-2 block text-sm font-medium text-gray-300"
              >
                Usuario
              </label>
              <select
                id="user"
                value={selectedUser}
                onChange={(e) => setSelectedUser(e.target.value)}
                className="w-full rounded-lg border border-slate-600 bg-slate-700 p-2.5 text-white transition-colors hover:border-slate-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              >
                {USER_COLUMNS.map((user) => (
                  <option key={user} value={user}>
                    {user}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label
                htmlFor="service"
                className="mb-2 block text-sm font-medium text-gray-300"
              >
                Servicio
              </label>
              <select
                id="service"
                value={serviceName}
                onChange={(e) => setServiceName(e.target.value)}
                className="w-full rounded-lg border border-blue-900/30 bg-gray-900/80 p-2.5 text-white focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              >
                {SERVICE_LIST.map((service) => (
                  <option key={service} value={service}>
                    {service}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label
                htmlFor="client"
                className="mb-2 block text-sm font-medium text-gray-300"
              >
                Cliente (Opcional)
              </label>
              <input
                type="text"
                id="client"
                value={client}
                onChange={(e) => setClient(e.target.value)}
                className="w-full rounded-lg border border-slate-600 bg-slate-700 p-2.5 text-white transition-colors hover:border-slate-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                placeholder="Nombre del cliente"
              />
            </div>

            <div>
              <label
                htmlFor="earnings"
                className="mb-2 block text-sm font-medium text-gray-300"
              >
                Ganancia
              </label>
              <input
                type="number"
                id="earnings"
                value={earnings}
                onChange={(e) => setEarnings(e.target.value)}
                className="w-full rounded-lg border border-slate-600 bg-slate-700 p-2.5 text-white transition-colors hover:border-slate-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                placeholder="Ej: 500"
                min="0"
                step="0.01"
              />
            </div>

            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setIsFormOpen(false)}
                className="rounded-lg border border-gray-600 bg-gray-700/50 px-6 py-2.5 text-sm font-medium text-gray-300 hover:bg-gray-700"
              >
                Cancelar
              </button>
              <button
                type="submit"
                disabled={loading}
                className="rounded-lg border border-green-900/30 bg-green-600/20 px-6 py-2.5 text-sm font-medium text-green-300 hover:bg-green-600/30 disabled:opacity-50"
              >
                {loading ? "Guardando..." : "Guardar"}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};

export default DataModificationForm;
